resources:
  - bases/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsclusters.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsmachines.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsmanagedclusters.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsmanagedclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
  - bases/rosaclusters.infrastructure.cluster.x-k8s.io.yaml
  - bases/rosamachinepools.infrastructure.cluster.x-k8s.io.yaml
  - bases/rosanetworks.infrastructure.cluster.x-k8s.io.yaml
  - bases/rosaroleconfigs.infrastructure.cluster.x-k8s.io.yaml
patches:
  - path: patches/versions/v1beta1/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclusterroleidentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclusterroleidentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclusterstaticidentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclusterstaticidentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclustertemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsclustertemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsfargateprofiles.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsfargateprofiles.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsmachines.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmachines.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsmachines.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmachines.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmachinetemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmachinetemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsmanagedclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmanagedclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsmanagedclustertemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmanagedclustertemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmanagedmachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: awsmanagedmachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/rosaclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: rosaclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/rosamachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: rosamachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/rosanetworks.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: rosanetworks.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta2/rosaroleconfigs.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: rosaroleconfigs.infrastructure.cluster.x-k8s.io
