apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capa-serving-cert'
    controller-gen.kubebuilder.io/version: v0.16.5
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" }}'
    cluster.x-k8s.io/provider: infrastructure-aws
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha4
    cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
    helm.sh/chart: '{{ .Chart.Name }}'
  name: awsmanagedclusters.infrastructure.cluster.x-k8s.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: '{{ .Release.Namespace }}'
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
        - v1beta1
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
      - cluster-api
    kind: AWSManagedCluster
    listKind: AWSManagedClusterList
    plural: awsmanagedclusters
    shortNames:
      - awsmc
    singular: awsmanagedcluster
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Cluster to which this AWSManagedControl belongs
          jsonPath: .metadata.labels.cluster\.x-k8s\.io/cluster-name
          name: Cluster
          type: string
        - description: Control plane infrastructure is ready for worker nodes
          jsonPath: .status.ready
          name: Ready
          type: string
        - description: API Endpoint
          jsonPath: .spec.controlPlaneEndpoint.host
          name: Endpoint
          priority: 1
          type: string
      name: v1beta2
      schema: {}
      served: true
      storage: true
      subresources:
        status: {}
