apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capa-serving-cert'
    controller-gen.kubebuilder.io/version: v0.16.5
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" }}'
    cluster.x-k8s.io/provider: infrastructure-aws
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha4
    cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
    helm.sh/chart: '{{ .Chart.Name }}'
  name: awsmachinepools.infrastructure.cluster.x-k8s.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: capa-webhook-service
          namespace: '{{ .Release.Namespace }}'
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
        - v1beta1
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
      - cluster-api
    kind: AWSMachinePool
    listKind: AWSMachinePoolList
    plural: awsmachinepools
    shortNames:
      - awsmp
    singular: awsmachinepool
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Machine ready status
          jsonPath: .status.ready
          name: Ready
          type: string
        - description: Machine ready status
          jsonPath: .status.replicas
          name: Replicas
          type: integer
        - description: Minimum instanes in ASG
          jsonPath: .spec.minSize
          name: MinSize
          type: integer
        - description: Maximum instanes in ASG
          jsonPath: .spec.maxSize
          name: MaxSize
          type: integer
        - description: Launch Template ID
          jsonPath: .status.launchTemplateID
          name: LaunchTemplate ID
          type: string
      name: v1beta1
      schema: {}
      served: false
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
        - description: Machine ready status
          jsonPath: .status.ready
          name: Ready
          type: string
        - description: Machine ready status
          jsonPath: .status.replicas
          name: Replicas
          type: integer
        - description: Minimum instanes in ASG
          jsonPath: .spec.minSize
          name: MinSize
          type: integer
        - description: Maximum instanes in ASG
          jsonPath: .spec.maxSize
          name: MaxSize
          type: integer
        - description: Launch Template ID
          jsonPath: .status.launchTemplateID
          name: LaunchTemplate ID
          type: string
      name: v1beta2
      schema: {}
      served: true
      storage: true
      subresources:
        status: {}
